### ISSUE TITLE
Folder semantic

### ISSUE THREAD

**Issue by gr-im** [Jauke/Du-Scales#1]
I have difficulty understanding why the directory "src" contiend only data structures.

**Comment by BilouMaster** [comment]
Well... c'est les data sources utilisées pour compiler la data finale. C'est saugrenu j'en conviens, je voulais ainsi les séparer mais je n'ai pas eu une meilleure idée que "src".

Au final, tout ce qui sera utilisé par l'application, c'est le data.js, généré par compile.js.
Je ne voulais pas que le client subisse les opérations du compile.js à chaque fois alors que c'est pour générer des données statiques qui ne bougeront plus.

Si tu as des suggestions, tu connais mon niveau de noobisme, je serais tout plaisir d'avoir de tes nouvelles.
