### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by gr-im** [Jauke/Du-Scales#2]
Ca commence à prendre forme ! 
Je trouve le design peu à mon goût, mais je ne saurais pas dire pourquoi ;) 

De quelle manière comptes-tu définir un pattern facile à réaliser à la main, as tu des idées de comment réussir à généraliser ça sous forme d'algorithme ?

**Comment by BilouMaster** [comment]
Salut Grim, et merci pour ce retour. :)

> Je trouve le design peu à mon goût, mais je ne saurais pas dire pourquoi ;)

Ca manque de simplicité, peut-être. :) Je me demande encore ce qui est le plus maléfique entre l'ombre et le dégradé. :D 

> De quelle manière comptes-tu définir un pattern facile à réaliser à la main, as tu des idées de comment réussir à généraliser ça sous forme d'algorithme ?

Les dessins que tu peux trouver actuellement sont déjà le fruit d'un premier algorithme qui peut interpréter toutes les gammes écrites [de cette manière](https://github.com/open-dualo/du-scales/blob/gh-pages/src/data/scales.json). ^^

La base de l'algorithme actuel est un peu bidon, c'est une application directe de [mes premières recherches](https://github.com/open-dualo/du-scales/tree/gh-pages/recherches). J'ai tenté de rendre mes recherches compréhensibles... en vain. Je rédige très prochainement un complément plus clair et concis. :D 

Pour l'algorithme actuel, tout est dans [data](https://github.com/open-dualo/du-scales/tree/gh-pages/src/data) :
- Dans [scales.json](https://github.com/open-dualo/du-scales/blob/gh-pages/src/data/scales.json), je rentre les gammes à déchiffrer.
- Dans [codage.json](https://github.com/open-dualo/du-scales/blob/gh-pages/src/data/codage.json), je rentre les données nécessaires au déchiffrage.
- Dans [combin.json](https://github.com/open-dualo/du-scales/blob/gh-pages/src/data/combin.json), je fais l'état des combinaisons possibles (gauche-droite) ainsi que les intervalles jugées improbables, pour faciliter l'exclusion.
- Dans [compile.js](https://github.com/open-dualo/du-scales/blob/gh-pages/src/data/compile.js), j'écris enfin l'algorithme qui utilise les données précédentes pour générer les différents "dessins" (tableaux d'indices) dans le fichier [data.js](https://github.com/open-dualo/du-scales/blob/gh-pages/src/data/data.js).

J'utilise node.js pour exécuter `compile.js` et écrire `data.js`.
Au final, `data.js` regroupe toutes les informations nécessaires au déploiement de l'application.

Mais ma démarche actuelle est loin d'être fiable. Je pense éventuellement à un nouvel algorithme, très différent, tenant compte du spectre des possibilités en fonction de chaque transposition... c'est pas évident. (d'autant plus que je ne vois pas encore si un outil mathématique peut m'être utile...)

Côté interface, l'actuelle permet de voir seulement la première variation de chaque gamme, mais on pourra très bientôt voir les variantes admissibles possibles s'il y en a.

Côté data, je n'ai répertorié que quelques gammes, mais je pense finir de toutes les répertorier pour mieux valider le prochain algo.

**Comment by BilouMaster** [comment]
Hier soir, j'ai trouvé une méthode de résolution qui rend toutes mes recherches précédentes inutiles... :)  

J'ai trouvé une démarche qui permet d'écrire et représenter euh...  
~cherche un nom barbare~  
Le...  
"_graphique de la loi normale de distribution des intervalles selon le principe dualo, par BilouMaster Joke, le 18 novembre 2015_".

Je vais en chier pour faire la démonstration... voici directement le résultat :

![](http://image.noelshack.com/fichiers/2015/47/1447946633-dualo-clavier-explication-codage7.png)
![](http://image.noelshack.com/fichiers/2015/47/1447946633-dualo-clavier-explication-codage6.png)

Maintenant j'ai hâte de ré-écrire mon algo pour simplement appliquer et vérifier cette loi. <3
